/*
 * JDialogEditBooking.java
 *
 * Created on October 3, 2005, 5:00 PM
 */

package myticket;

import java.io.*;
import javax.swing.*;
import javax.swing.event.*;

/**
 *
 * @author  sdperret
 */
public class JDialogEditBooking extends javax.swing.JDialog {
    
    /** Creates new form JDialogEditBooking */
    public JDialogEditBooking( Booking aBooking, BookingSystem aBookingSystem, JDialog aDialog ) {
        
        super( aDialog, true ); 
        
        myTicket = aBookingSystem;
        booking = aBooking;
        previousDialog = aDialog;
        
       
        
        initComponents();
        
        
        jSpinnerNbSeats.setModel( new SpinnerNumberModel( booking.getNbSeats(), 0, (booking.getPerformance().getNbFreeSeats() + booking.getNbSeats() ) , 1) );
        
        TableModelListener toto = new TableModelListener( ){
            public void tableChanged( TableModelEvent e ){

                //jLabelNbFreeSeats.setText( booking.getPerformance().getNbFreeSeats() + " seats free + " + booking.getNbSeats() + " seats booked below = " + (booking.getPerformance().getNbFreeSeats() + booking.getNbSeats()) + " seats available for booking");
                jLabelNbFreeSeats1.setText( (booking.getPerformance().getNbFreeSeats() + booking.getNbSeats() ) + " seats free");

            }
        };
        myTicket.getPerformances().addTableModelListener( toto );
        
        jTextFieldName.setText( booking.getClient().getName().substring(0, Math.min(35, booking.getClient().getName().length() ) ) );
        jSpinnerNbSeats.setValue( booking.getNbSeats() );
        jTextFieldStreet.setText( booking.getClient().getStreet() );
        jTextFieldTown.setText( booking.getClient().getTown());
        jTextFieldPhone.setText( booking.getClient().getPhone());
        jTextFieldEmail.setText( booking.getClient().getEmail());
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerNbSeats = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldComment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldStreet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTown = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonOK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelNbFreeSeats1 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(java.util.ResourceBundle.getBundle( "myticket/BundleMyTicket", key.Preferrences.getLocale() ).getString("labelNameDPSPM" ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextFieldName.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldName.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldName.setPreferredSize(new java.awt.Dimension(300, 25));
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jTextFieldName, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(java.util.ResourceBundle.getBundle( "myticket/BundleMyTicket", key.Preferrences.getLocale() ).getString("labelNbSeatsDPSPM" ));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel2, gridBagConstraints);

        jSpinnerNbSeats.setFont(new java.awt.Font("Dialog", 0, 18));
        jSpinnerNbSeats.setMinimumSize(new java.awt.Dimension(28, 25));
        jSpinnerNbSeats.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jSpinnerNbSeats, gridBagConstraints);

        jSeparator1.setPreferredSize(new java.awt.Dimension(20, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel1.add(jSeparator1, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(java.util.ResourceBundle.getBundle( "myticket/BundleMyTicket", key.Preferrences.getLocale() ).getString("labelCommentDPSPM" ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel3, gridBagConstraints);

        jTextFieldComment.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldComment.setText(booking.getComment());
        jTextFieldComment.setMinimumSize(new java.awt.Dimension(4, 23));
        jTextFieldComment.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jTextFieldComment, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(java.util.ResourceBundle.getBundle( "myticket/BundleMyTicket", key.Preferrences.getLocale() ).getString("labelStreetDBSP" ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel4, gridBagConstraints);

        jTextFieldStreet.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldStreet.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldStreet.setPreferredSize(new java.awt.Dimension(300, 25));
        jTextFieldStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStreetActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jTextFieldStreet, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(java.util.ResourceBundle.getBundle( "myticket/BundleMyTicket", key.Preferrences.getLocale() ).getString("labelTownDPSP" ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel5, gridBagConstraints);

        jTextFieldTown.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldTown.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldTown.setPreferredSize(new java.awt.Dimension(300, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jTextFieldTown, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText(java.util.ResourceBundle.getBundle( "myticket/BundleMyTicket", key.Preferrences.getLocale() ).getString("labelPhoneNumberDPSP" ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel6, gridBagConstraints);

        jTextFieldPhone.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldPhone.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldPhone.setPreferredSize(new java.awt.Dimension(300, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jTextFieldPhone, gridBagConstraints);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(java.util.ResourceBundle.getBundle( "myticket/BundleMyTicket", key.Preferrences.getLocale() ).getString("labelEmailDPSPM" ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel7, gridBagConstraints);

        jTextFieldEmail.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldEmail.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldEmail.setPreferredSize(new java.awt.Dimension(300, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jTextFieldEmail, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel3.add(jSeparator2);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel4.add(jButtonCancel);

        jSeparator3.setPreferredSize(new java.awt.Dimension(300, 0));
        jPanel4.add(jSeparator3);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanel4.add(jButtonOK);

        jPanel3.add(jPanel4);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel18.setText(booking.getPerformance().getShow().getTitle());
        jPanel2.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel19.setText(booking.getPerformance().getShow().getPerformer().getName());
        jPanel2.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel20.setText(booking.getPerformance().getRoom().getCompany().getName());
        jPanel2.add(jLabel20);

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel21.setText(booking.getPerformance().getFormatedDate());
        jPanel2.add(jLabel21);

        jLabelNbFreeSeats1.setText((booking.getPerformance().getNbFreeSeats() + booking.getNbSeats() ) + " seats free ");
        jPanel2.add(jLabelNbFreeSeats1);

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setMinimumSize(new java.awt.Dimension(0, 10));
        jSeparator12.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel2.add(jSeparator12);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
// TODO add your handling code here:
        if( jTextFieldName.getText().length() > 35 ){
            java.awt.Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStreetActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStreetActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
// TODO add your handling code here:
        try{
            try{
                if( (Integer) jSpinnerNbSeats.getValue() <= (booking.getPerformance().getNbFreeSeats() + booking.getNbSeats() ) ){            
                    booking.updateBooking( jTextFieldName.getText(), (Integer) jSpinnerNbSeats.getValue(), jTextFieldComment.getText(), jTextFieldStreet.getText(), jTextFieldTown.getText(), jTextFieldPhone.getText(), jTextFieldEmail.getText() );
                    
                    //previousDialog.getBookings().fireTableChanged( new TableModelEvent( previousDialog.getBookings() ) );
                    
                    /*previousDialog.getBookings().fireTableDataChanged();
                    myTicket.getPerformances().fireTableDataChanged();
                    booking.getPerformance().getBookings().fireTableDataChanged();*/
                    myTicket.getPerformances().fireTableDataChanged();
                    booking.getPerformance().getBookings().fireTableDataChanged();
                    //previousDialog.getSorter().fireTableDataChanged();
                    dispose();
                }else{
                    JOptionPane.showMessageDialog( null, "Cannot book so many seats" + " seats. Only " + (booking.getPerformance().getNbFreeSeats() + booking.getNbSeats() ) + " seat(s) available for booking", "Booking error", JOptionPane.OK_OPTION );
                }
            }catch( PerformanceFullException e ){
                JOptionPane.showMessageDialog( null, "Cannot book so many seats" + " seats. Only " + (booking.getPerformance().getNbFreeSeats() + booking.getNbSeats() ) + " seat(s) available for booking", "Booking error", JOptionPane.OK_OPTION );
            }
        }catch( IOException e2 ){
            JOptionPane.showMessageDialog( null, "Could not write to file, canceling change", "System error", JOptionPane.OK_OPTION );
        }
        
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JDialogEditBooking( new Booking() ).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNbFreeSeats1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinnerNbSeats;
    private javax.swing.JTextField jTextFieldComment;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldStreet;
    private javax.swing.JTextField jTextFieldTown;
    // End of variables declaration//GEN-END:variables
 
    Booking booking = null;
    BookingSystem myTicket = null;
    JDialog previousDialog;
    
}
