/*
 * JFrameSelling.java
 *
 * Created on October 2, 2005, 11:42 AM
 */

package myticket;

import javax.swing.event.*;
import javax.swing.text.*;
import javax.swing.*;
import java.io.*;

import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;


import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;
import java.io.*;
import javax.swing.event.*;
import javax.swing.text.*;
import javax.swing.*;
import java.util.Date;

/**
 *
 * @author  sdperret
 */
public class JDialogSelling extends javax.swing.JDialog {
    
    /** Creates new form JFrameSelling */
    public JDialogSelling( Booking aBooking, BookingSystem aBookingSystem, JDialog aDialog ) {
        super( aDialog, true );
        
        booking = aBooking;
        myTicket = aBookingSystem;
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelC1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldReceived = new javax.swing.JTextField();
        jLabelC2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelReturn = new javax.swing.JLabel();
        jLabelC3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jButtonCancel.setText("Cancel Tickets");
        jButtonCancel.setEnabled(false);
        jButtonCancel.setPreferredSize(new java.awt.Dimension(124, 18));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonCancel);

        jSeparator1.setPreferredSize(new java.awt.Dimension(30, 0));
        jPanel3.add(jSeparator1);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Price:");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 15));
        jPanel4.add(jLabel1);

        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrice.setText(Double.toString( booking.getSumPrice() ));
        jLabelPrice.setPreferredSize(new java.awt.Dimension(100, 15));
        jPanel4.add(jLabelPrice);

        jLabelC1.setText(booking.getPerformance().getCurrency());
        jLabelC1.setPreferredSize(new java.awt.Dimension(60, 15));
        jPanel4.add(jLabelC1);

        jPanel1.add(jPanel4);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Received:");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 15));
        jPanel5.add(jLabel4);

        jTextFieldReceived.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldReceived.setText("");

        jTextFieldReceived.getDocument().addDocumentListener(

            new DocumentListener(){
                public void insertUpdate( DocumentEvent event ){

                    Document a = event.getDocument();
                    try{
                        String t = a.getText(0, a.getLength() );

                        if( t.length() > 0 ){

                            Double d = 0.0;
                            try{
                                d = Double.parseDouble( t );

                                if( t.length() > 0 ){
                                    if( d - booking.getSumPrice()  >= 0 ){
                                        jLabelReturn.setText( Double.toString( d - booking.getSumPrice() ) );
                                    }else{
                                        jLabelReturn.setText( "Not enough" );
                                    }
                                }else{
                                    jLabelReturn.setText( "" );
                                }

                            }catch( NumberFormatException ne ){

                                jLabelReturn.setText( "" );
                            }

                        }else{
                            jLabelReturn.setText( "Not enough" );
                        }

                    } catch(  BadLocationException e ){

                    }
                }

                public void removeUpdate( DocumentEvent event ){
                    Document a = event.getDocument();
                    try{
                        String t = a.getText(0, a.getLength() );

                        if( t.length() > 0 ){

                            Double d = 0.0;
                            try{
                                d = Double.parseDouble( t );

                                if( t.length() > 0 ){
                                    if( d - booking.getSumPrice()  >= 0 ){
                                        jLabelReturn.setText( Double.toString( d - booking.getSumPrice() ) );
                                    }else{
                                        jLabelReturn.setText( "Not enough" );
                                    }
                                }else{
                                    jLabelReturn.setText( "" );
                                }

                            }catch( NumberFormatException ne ){

                                jLabelReturn.setText( "" );
                            }
                        }else{
                            jLabelReturn.setText( "Not enough" );
                        }

                    } catch(  BadLocationException e ){

                    }
                }
                public void changedUpdate( DocumentEvent event) {}

            }

        );
        jTextFieldReceived.setPreferredSize(new java.awt.Dimension(100, 19));
        jTextFieldReceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldReceivedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldReceivedKeyReleased(evt);
            }
        });

        jPanel5.add(jTextFieldReceived);

        jLabelC2.setText(booking.getPerformance().getCurrency());
        jLabelC2.setPreferredSize(new java.awt.Dimension(60, 15));
        jPanel5.add(jLabelC2);

        jPanel1.add(jPanel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Return:");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 15));
        jPanel6.add(jLabel6);

        jLabelReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelReturn.setMinimumSize(new java.awt.Dimension(100, 15));
        jLabelReturn.setPreferredSize(new java.awt.Dimension(100, 15));
        jPanel6.add(jLabelReturn);

        jLabelC3.setText(booking.getPerformance().getCurrency());
        jLabelC3.setPreferredSize(new java.awt.Dimension(60, 15));
        jPanel6.add(jLabelC3);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jTextFieldReceivedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldReceivedKeyReleased
// TODO add your handling code here:
        
      char c = evt.getKeyChar();      
      if (!((Character.isDigit(c) || (c == KeyEvent.VK_ENTER) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) )) {
        getToolkit().beep();
        evt.consume();
        //jTextFieldReceived.setText( "" );
      }
      
    }//GEN-LAST:event_jTextFieldReceivedKeyReleased

    private void jTextFieldReceivedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldReceivedKeyPressed
// TODO add your handling code here:
        
        
      
        
        
    }//GEN-LAST:event_jTextFieldReceivedKeyPressed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// TODO add your handling code here:
        
      /*  try{
            //booking.writeTickets( "UNSELL" );
            booking.unsellTickets();
            
            String message = "Tickets: ";
        
            for( Ticket t : booking.getTickets() ){
                message += t.getId() + ", ";
            }
            message += " where CANCELED, please destroy these tickets";   
        
            JOptionPane.showMessageDialog( null, message, "Canceling tickets", JOptionPane.OK_OPTION );
            
        }catch( java.io.IOException e ){
            JOptionPane.showMessageDialog( null, "COULD NOT CANCEL sell from file.", "Booking error", JOptionPane.OK_OPTION );           
        }
        
        
            
        
        booking.cancelPrebooking();
        myTicket.getPerformances().fireTableDataChanged();*/
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JFrameSelling( new Booking(), new BookingSystem( new File( "/home/sdperret") ), new JFrame() ).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelC1;
    private javax.swing.JLabel jLabelC2;
    private javax.swing.JLabel jLabelC3;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldReceived;
    // End of variables declaration//GEN-END:variables
    
    Booking booking = null;
    BookingSystem myTicket;
}
