/*
 * JFrameKeyDataInput.java
 *
 * Created on October 23, 2005, 12:09 PM
 */

package bouboutelkeygen;

import java.security.*;
import java.util.Arrays;
import java.io.*;


/**
 *
 * @author  sdperret
 */
public class JFrameKeyDataInput extends javax.swing.JFrame {
    
    /** Creates new form JFrameKeyDataInput */
    public JFrameKeyDataInput() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelSouth = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldProgramName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVersion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMonth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldFilename = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel7.setText("BOUBOUTEL License file generator");
        jPanel1.add(jLabel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanelSouth.add(jButtonOK);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Software name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jLabel9, gridBagConstraints);

        jTextFieldProgramName.setText("bouboutel");
        jTextFieldProgramName.setMinimumSize(new java.awt.Dimension(100, 19));
        jTextFieldProgramName.setPreferredSize(new java.awt.Dimension(100, 19));
        jTextFieldProgramName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProgramNameActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jTextFieldProgramName, gridBagConstraints);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Version: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jLabel10, gridBagConstraints);

        jTextFieldVersion.setText("1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jTextFieldVersion, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nom de l'organisation: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jLabel1, gridBagConstraints);

        jTextFieldName.setMinimumSize(new java.awt.Dimension(100, 19));
        jTextFieldName.setPreferredSize(new java.awt.Dimension(400, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanelCenter.add(jTextFieldName, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Validity Limit (DD : MM : YYYY): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jLabel2, gridBagConstraints);

        jTextFieldDay.setMinimumSize(new java.awt.Dimension(40, 19));
        jTextFieldDay.setPreferredSize(new java.awt.Dimension(40, 19));
        jPanelCenter.add(jTextFieldDay, new java.awt.GridBagConstraints());

        jLabel3.setText(":");
        jPanelCenter.add(jLabel3, new java.awt.GridBagConstraints());

        jTextFieldMonth.setMinimumSize(new java.awt.Dimension(40, 19));
        jTextFieldMonth.setPreferredSize(new java.awt.Dimension(40, 19));
        jPanelCenter.add(jTextFieldMonth, new java.awt.GridBagConstraints());

        jLabel4.setText(":");
        jPanelCenter.add(jLabel4, new java.awt.GridBagConstraints());

        jTextFieldYear.setMinimumSize(new java.awt.Dimension(40, 19));
        jTextFieldYear.setPreferredSize(new java.awt.Dimension(40, 19));
        jPanelCenter.add(jTextFieldYear, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanelCenter.add(jLabel5, gridBagConstraints);

        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanelCenter.add(jSeparator1, gridBagConstraints);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Key store password: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jLabel8, gridBagConstraints);

        jPasswordField.setPreferredSize(new java.awt.Dimension(400, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jPasswordField, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Save Key file as: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCenter.add(jLabel6, gridBagConstraints);

        jTextFieldFilename.setText("key.dat");
        jTextFieldFilename.setPreferredSize(new java.awt.Dimension(400, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanelCenter.add(jTextFieldFilename, gridBagConstraints);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jTextFieldProgramNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProgramNameActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProgramNameActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
// TODO add your handling code here:
        
        
        // get in my own private key
        //KeyStore store = Keystore.getInstance("JKS", "SUN");
        try{
            KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
        
            char[] password = jPasswordField.getPassword();
            try{
                //java.io.FileInputStream fis = new java.io.FileInputStream("/home/sdperret/.keystore");
                java.io.FileInputStream fis = new java.io.FileInputStream("/Users/jlp/.keystore");
                try{ 
                    try{
                        try{
                            ks.load(fis, password);
                            fis.close();
        
        
                            try{
                                PrivateKey myPriv = (PrivateKey) ks.getKey( "bouboutel", password );
                                Arrays.fill( password, ' ');
                                
                                int day = Integer.parseInt(jTextFieldDay.getText());
                                
                                
                                try{
                                    key.License license = new key.License( 
                                        jTextFieldProgramName.getText(),
                                        Float.parseFloat( jTextFieldVersion.getText() ),
                                        jTextFieldName.getText(), 
                                        Integer.parseInt(jTextFieldDay.getText()), 
                                        Integer.parseInt(jTextFieldMonth.getText()), 
                                        Integer.parseInt(jTextFieldYear.getText()), 
                                        myPriv );
                                    
                                    
                                   license.save( new File( jTextFieldFilename.getText() ) ); 
                                           
                                   dispose();
                                    
                                }catch( Exception e ){
                                    System.out.println( "creating licence error: " + e );
                                }
                                
                              
                                
                                
                                
                                // write data to file
                                
                                
        
                            }catch( java.security.UnrecoverableKeyException e6 ){
                                System.out.println( "e6 " + e6 );
                            }
                        }catch( java.security.cert.CertificateException e5 ){
                            System.out.println( "e5 "+ e5 );
                        }
                    }catch( java.security.NoSuchAlgorithmException e4 ){
                        System.out.println( "e4 " + e4 );
                    }
                }catch( java.io.IOException e3 ){
                    System.out.println( "e3 " + e3 );
                }
            }catch( java.io.FileNotFoundException e2 ){
                System.out.println( "e2 " +e2 );
            }
        }catch( KeyStoreException e ){
            System.out.println( "e " + e );
        }
        
        
        
        
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameKeyDataInput().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldFilename;
    private javax.swing.JTextField jTextFieldMonth;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldProgramName;
    private javax.swing.JTextField jTextFieldVersion;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
    
}
