/*
 * JDialogEditBooking.java
 *
 * Created on October 3, 2005, 5:00 PM
 */
package ch.poudriere.bouboutel.ui;

import ch.poudriere.bouboutel.bundles.I18n;
import ch.poudriere.bouboutel.exceptions.BackupAccessException;
import ch.poudriere.bouboutel.files.BookingFile;
import ch.poudriere.bouboutel.files.Data;
import ch.poudriere.bouboutel.models.Booking;
import ch.poudriere.bouboutel.models.BookingSystem;
import ch.poudriere.bouboutel.models.Performance;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.*;

/**
 *
 * @author sdperret
 */
public class JDialogEditBooking extends javax.swing.JDialog {
    private final BookingSystem bookingSystem;
    private final Booking booking;
    private final Performance performance;

    public JDialogEditBooking(JDialog parent, Booking booking) {
        super(parent, true);
        bookingSystem = BookingSystem.getInstance();
        this.booking = booking;
        this.performance = booking.getPerformance();

        initComponents();

        int nbSeats = booking.getNbSeats();
        int maxSeats = booking.getPerformance().getNbFreeSeats()
                + booking.getNbSeats();
        jSpinnerNbSeats.
                setModel(new SpinnerNumberModel(nbSeats, 0, maxSeats, 1));

        jTextFieldName.setText(booking.getCustomerName().substring(0, Math.
                min(35, booking.getCustomerName().length())));
        jSpinnerNbSeats.setValue(booking.getNbSeats());
        jTextFieldComment.setText(booking.getComment());
        jTextFieldPhone.setText(booking.getCustomerPhone());

        InputMap im = getRootPane().getInputMap(
                JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = getRootPane().getActionMap();
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "cancel");
        am.put("cancel", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerNbSeats = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldComment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jPanelPerformance = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelNbFreeSeats2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, javax.swing.UIManager.getDefaults().getColor("Button.borderColor")));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setText(I18n.get("label.name" )); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextFieldName.setFont(jTextFieldName.getFont().deriveFont(jTextFieldName.getFont().getSize()+2f));
        jTextFieldName.setMinimumSize(new java.awt.Dimension(300, 30));
        jTextFieldName.setPreferredSize(new java.awt.Dimension(300, 30));
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldName, gridBagConstraints);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+2f));
        jLabel2.setText(I18n.get("label.nbSeats" )); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        jPanel1.add(jLabel2, gridBagConstraints);

        jSpinnerNbSeats.setFont(jSpinnerNbSeats.getFont().deriveFont(jSpinnerNbSeats.getFont().getSize()+2f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jSpinnerNbSeats, gridBagConstraints);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+2f));
        jLabel3.setText(I18n.get("labelComment" )); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        jPanel1.add(jLabel3, gridBagConstraints);

        jTextFieldComment.setFont(jTextFieldComment.getFont().deriveFont(jTextFieldComment.getFont().getSize()+2f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldComment, gridBagConstraints);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+2f));
        jLabel6.setText(I18n.get("labelPhone" )); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        jPanel1.add(jLabel6, gridBagConstraints);

        jTextFieldPhone.setFont(jTextFieldPhone.getFont().deriveFont(jTextFieldPhone.getFont().getSize()+2f));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldPhone, gridBagConstraints);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/poudriere/bouboutel/bundles/I18n"); // NOI18N
        jButtonCancel.setText(bundle.getString("buttonCancel")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanelPerformance.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPerformance.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelPerformance.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(jLabel14.getFont().deriveFont(jLabel14.getFont().getStyle() | java.awt.Font.BOLD, jLabel14.getFont().getSize()+10));
        jLabel14.setText(performance.getShow().getTitle());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanelPerformance.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getSize()+4f));
        jLabel15.setText(performance.getShow().getCompany().getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanelPerformance.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(jLabel16.getFont().deriveFont(jLabel16.getFont().getSize()+4f));
        jLabel16.setText(performance.getRoom().getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPerformance.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()+4f));
        jLabel17.setText(I18n.formatDate(performance.getDate()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPerformance.add(jLabel17, gridBagConstraints);

        jLabelNbFreeSeats2.setFont(jLabelNbFreeSeats2.getFont().deriveFont(jLabelNbFreeSeats2.getFont().getStyle() | java.awt.Font.BOLD, jLabelNbFreeSeats2.getFont().getSize()+6));
        jLabelNbFreeSeats2.setForeground(new java.awt.Color(191, 23, 29));
        jLabelNbFreeSeats2.setText(performance.getNbFreeSeats() + " seats free");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanelPerformance.add(jLabelNbFreeSeats2, gridBagConstraints);

        getContentPane().add(jPanelPerformance, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
// TODO add your handling code here:
        if (jTextFieldName.getText().length() > 35) {
            java.awt.Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        if ((Integer) jSpinnerNbSeats.getValue() > (booking.
                getPerformance().getNbFreeSeats() + booking.getNbSeats())) {
            JOptionPane.showMessageDialog(null,
                    "Cannot book so many seats" + " seats. Only "
                    + (booking.getPerformance().getNbFreeSeats()
                    + booking.getNbSeats())
                    + " seat(s) available for booking", "Booking error",
                    JOptionPane.OK_OPTION);
            return;
        }

        try {
            Data oldData = booking.asData(BookingFile.Command.UPDATEBOOKING);
            booking.setCustomerName(jTextFieldName.getText());
            booking.setCustomerPhone(jTextFieldPhone.getText());
            booking.setComment(jTextFieldComment.getText());
            booking.setNbSeats((Integer) jSpinnerNbSeats.getValue());
            Data newData = booking.asData(BookingFile.Command.UPDATEBOOKING);
            if (!newData.toString().equals(oldData.toString())) {
                performance.updateDataFile(booking.asData(
                        BookingFile.Command.UPDATEBOOKING));
            }
            dispose();

        } catch (IOException | BackupAccessException e2) {
            JOptionPane.showMessageDialog(null,
                    "Could not write to file, canceling change", "System error",
                    JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelNbFreeSeats2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPerformance;
    private javax.swing.JSpinner jSpinnerNbSeats;
    private javax.swing.JTextField jTextFieldComment;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
