/*
 * JFrameSelling.java
 *
 * Created on October 2, 2005, 11:42 AM
 */
package ch.poudriere.bouboutel.ui;

import ch.poudriere.bouboutel.bundles.I18n;
import ch.poudriere.bouboutel.models.BookingSystem;
import ch.poudriere.bouboutel.models.Ticket;
import ch.poudriere.bouboutel.utils.Preferences;
import java.util.List;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author sdperret
 */
public class JDialogSelling extends javax.swing.JDialog {
    private final BookingSystem bookingSystem;
    private final List<Ticket> tickets;
    private final Double totalAmount;

    public JDialogSelling(JDialog parent, List<Ticket> tickets) {
        super(parent, true);
        bookingSystem = BookingSystem.getInstance();
        this.tickets = tickets;
        totalAmount = tickets.stream().mapToDouble(
                t -> t.getPrice()).sum();

        initComponents();

        jLabelPrice.setText(I18n.getCurrencyFormat().format(totalAmount));

        jTextFieldReceived.getDocument().addDocumentListener(
                new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent event) {
                compute();
            }

            @Override
            public void removeUpdate(DocumentEvent event) {
                compute();
            }

            @Override
            public void changedUpdate(DocumentEvent event) {
                compute();
            }
        });
    }

    private void compute() {
        try {
            Double amount = Double.valueOf(jTextFieldReceived.getText());
            Double returnAmount = amount - totalAmount;
            if (returnAmount < 0.) {
                jLabelReturn.setText("Montant insuffisant");
            } else {
                jLabelReturn.setText(I18n.getCurrencyFormat().format(
                        returnAmount));
            }
        } catch (NumberFormatException ex) {
            jLabelReturn.setText("Montant invalide");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldReceived = new javax.swing.JTextField();
        jLabelC2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelReturn = new javax.swing.JLabel();
        jLabelC3 = new javax.swing.JLabel();
        jLabelC4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 10, 0, 10, 0};
        jPanel2Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setText("Prix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabelPrice.setFont(jLabelPrice.getFont().deriveFont(jLabelPrice.getFont().getSize()+2f));
        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabelPrice, gridBagConstraints);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+2f));
        jLabel4.setText("Reçu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabel4, gridBagConstraints);

        jTextFieldReceived.setFont(jTextFieldReceived.getFont().deriveFont(jTextFieldReceived.getFont().getSize()+2f));
        jTextFieldReceived.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldReceived.setText("");
        //jTextFieldReceived.getDocument().addDocumentListener(
            //
            //            new DocumentListener(){
                //                public void insertUpdate( DocumentEvent event ){
                    //
                    //                    Document a = event.getDocument();
                    //                    try{
                        //                        String t = a.getText(0, a.getLength() );
                        //
                        //                        if( t.length() > 0 ){
                            //
                            //                            Double d = 0.0;
                            //                            try{
                                //                                d = Double.parseDouble( t );
                                //
                                //                                if( t.length() > 0 ){
                                    //                                    if( d - booking.getSumPrice()  >= 0 ){
                                        //                                        jLabelReturn.setText( Double.toString( d - booking.getSumPrice() ) );
                                        //                                    }else{
                                        //                                        jLabelReturn.setText( "Not enough" );
                                        //                                    }
                                    //                                }else{
                                    //                                    jLabelReturn.setText( "" );
                                    //                                }
                                //
                                //                            }catch( NumberFormatException ne ){
                                //
                                //                                jLabelReturn.setText( "" );
                                //                            }
                            //
                            //                        }else{
                            //                            jLabelReturn.setText( "Not enough" );
                            //                        }
                        //
                        //                    } catch(  BadLocationException e ){
                        //
                        //                    }
                    //                }
                //
                //                public void removeUpdate( DocumentEvent event ){
                    //                    Document a = event.getDocument();
                    //                    try{
                        //                        String t = a.getText(0, a.getLength() );
                        //
                        //                        if( t.length() > 0 ){
                            //
                            //                            Double d = 0.0;
                            //                            try{
                                //                                d = Double.parseDouble( t );
                                //
                                //                                if( t.length() > 0 ){
                                    //                                    if( d - booking.getSumPrice()  >= 0 ){
                                        //                                        jLabelReturn.setText( Double.toString( d - booking.getSumPrice() ) );
                                        //                                    }else{
                                        //                                        jLabelReturn.setText( "Not enough" );
                                        //                                    }
                                    //                                }else{
                                    //                                    jLabelReturn.setText( "" );
                                    //                                }
                                //
                                //                            }catch( NumberFormatException ne ){
                                //
                                //                                jLabelReturn.setText( "" );
                                //                            }
                            //                        }else{
                            //                            jLabelReturn.setText( "Not enough" );
                            //                        }
                        //
                        //                    } catch(  BadLocationException e ){
                        //
                        //                    }
                    //                }
                //                public void changedUpdate( DocumentEvent event) {}
                //
                //            }
            //
            //        );
        jTextFieldReceived.setMinimumSize(new java.awt.Dimension(200, 26));
        jTextFieldReceived.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jTextFieldReceived, gridBagConstraints);

        jLabelC2.setFont(jLabelC2.getFont().deriveFont(jLabelC2.getFont().getSize()+2f));
        jLabelC2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelC2.setText(Preferences.getCurrency().getCurrencyCode());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabelC2, gridBagConstraints);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+2f));
        jLabel6.setText("À rendre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabelReturn.setFont(jLabelReturn.getFont().deriveFont(jLabelReturn.getFont().getStyle() | java.awt.Font.BOLD, jLabelReturn.getFont().getSize()+2));
        jLabelReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelReturn.setMinimumSize(new java.awt.Dimension(100, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabelReturn, gridBagConstraints);

        jLabelC3.setFont(jLabelC3.getFont().deriveFont(jLabelC3.getFont().getSize()+2f));
        jLabelC3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelC3.setText(Preferences.getCurrency().getCurrencyCode());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabelC3, gridBagConstraints);

        jLabelC4.setFont(jLabelC4.getFont().deriveFont(jLabelC4.getFont().getSize()+2f));
        jLabelC4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelC4.setText(Preferences.getCurrency().getCurrencyCode());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabelC4, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOK);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelC2;
    private javax.swing.JLabel jLabelC3;
    private javax.swing.JLabel jLabelC4;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelReturn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldReceived;
    // End of variables declaration//GEN-END:variables
}
