/*
 * Login.java
 *
 * Created on October 28, 2005, 8:04 AM
 */
package ch.poudriere.bouboutel.ui;

import ch.poudriere.bouboutel.utils.Preferences;
import javax.swing.*;

/**
 *
 * @author sdperret
 */
public class JDialogLogin extends javax.swing.JDialog {
    private boolean ok = false;

    /**
     * Creates new form Login
     *
     * @param parent
     */
    public JDialogLogin(JFrame parent) {
        super(parent, "Authentification", true);
        initComponents();
        getRootPane().setDefaultButton(jButton1);
        setLocationRelativeTo(parent);
        setVisible(true);
        requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/poudriere/bouboutel/bundles/I18n", Preferences.getLocale() ); // NOI18N
        jLabel2.setText(bundle.getString("labelPassword" )); // NOI18N
        jPanel2.add(jLabel2);

        jPasswordField.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel2.add(jPasswordField);

        getContentPane().add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton2.setText(bundle.getString("buttonCancel" )); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton1.setText(bundle.getString("buttonOK" )); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public boolean isOK() {
        return ok;
    }

    public String getPassword() {
        return new String(jPasswordField.getPassword());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
